In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

%matplotlib inline

In [13]:
df = pd.read_csv('data/twitter_data_sample.csv', index_col = 0)
df.head()

,user,location,txt,user_id,tweet_id,date,geo
0,BstKept_Secret,Your wildest dreams,RT @JUSMITHOUGHTS1: Fellas your lady send you ...,386971636,1400603202135941120,2021-06-03 23:59:59,NaN
1,fer_schez,"Manhattan, NY",#NowPlaying  #AppleMusic \n🔊 Rolling In the D...,67189705,1400603202031063043,2021-06-03 23:59:59,NaN
2,GuiRequiel,NaN,"RT @FieldYates: Happy 40th birthday, McLovin. ...",186896873,1400603201699827716,2021-06-03 23:59:59,NaN
3,Restore_NewYork,New York,RT @CurtisSliwa: It is time to kick lying poli...,1104621094122737664,1400603201683001351,2021-06-03 23:59:59,NaN
4,cee_jay_2016,NaN,RT @malcolmkenyatta: #Pride is protecting the ...,4614153192,1400603201557045255,2021-06-03 23:59:59,NaN

In [15]:
df.loc[df.geo.notnull(), :]

,user,location,txt,user_id,tweet_id,date,geo
405,CROSSMARKJobs,"Plano, TX",Can you recommend anyone for this job? RETAIL ...,36039488,1400603159827865601,2021-06-03 23:59:49,"{'type': 'Point', 'coordinates': [40.1784422, ..."
456,JeffreyHines80,NaN,I’m not a big fan of oatmeal except when it is...,717863903305326592,1400603153817612290,2021-06-03 23:59:48,"{'type': 'Point', 'coordinates': [39.8814468, ..."
1085,511NY,New York State,Cleared: Incident on #HutchinsonRiverParkwayWe...,50706690,1400603084297060353,2021-06-03 23:59:31,"{'type': 'Point', 'coordinates': [40.980899, -..."
1086,511NY,New York State,Incident on #NJ17 NB at South of Franklin Av h...,50706690,1400603084271853568,2021-06-03 23:59:31,"{'type': 'Point', 'coordinates': [40.853995, -..."
1105,511NY,New York State,Cleared: Incident on #NewJerseyTurnpike at Int...,50706690,1400603083152015362,2021-06-03 23:59:31,"{'type': 'Point', 'coordinates': [40.66898, -7..."
...,...,...,...,...,...,...,...
58598,GAGA_glitz,NJ/Mons†er Kingdom,Triumph opened and we hopped to it!! So glad t...,32316130,1400596609918963713,2021-06-03 23:33:48,"{'type': 'Point', 'coordinates': [40.3652267, ..."
59067,511NYMidHudson,Catskills,Incident on #TaconicStateParkway NB at Exit 17...,50728535,1400596557729312772,2021-06-03 23:33:35,"{'type': 'Point', 'coordinates': [41.2952, -73..."
59112,CTDOT_Statewide,Connecticut,Delays - NORWALK #I95 North 0.50 miles beyond ...,97036677,1400596553866387456,2021-06-03 23:33:34,"{'type': 'Point', 'coordinates': [41.110985, -..."
59113,CTDOT_District3,Southwestern Connecticut,Delays - NORWALK #I95 North 0.50 miles beyond ...,97034575,1400596553740566535,2021-06-03 23:33:34,"{'type': 'Point', 'coordinates': [41.110985, -..."
59938,pop_amargaritav,"Connecticut, USA","Why people obsessed so much with age , we know...",184529264,1400596463848148993,2021-06-03 23:33:13,"{'type': 'Point', 'coordinates': [41.3089, -72..."

In [5]:
user_with_geo = pd.unique(df_geo.user)
number_of_user_with_geo = len(pd.unique(df_geo.user))
print(user_with_geo)
print(number_of_user_with_geo)

['CROSSMARKJobs' 'JeffreyHines80' '511NY' '511NYMidHudson'
 'Manhattanpeachy' 'robbwil1' 'CTDOT_District1' 'CTDOT_Statewide'
 'shellfaber6' 'XclusiveArrival' 'HalterTop34' 'kyny889' 'iamnatemyles'
 'rocdabroski' 'josephmariko' 'chrisiestyles' 'RockStarr65'
 'coachmlewis33' 'TotalTrafficPHL' 'BlazeMusicNet' 'LsarowarRBLX2nd'
 'BGWritesStuff' 'BKSoulStew' 'j_rakowski' 'WWFarmersMarket'
 'DeWittGodfrey' 'rchiarellajewel' 'NWS_MountHolly' 'NWSSevereTstorm'
 'Devilsfan79' 'algattullo' 'iembot_phi' 'yankee32879' 'adampicz'
 'KennethFerrone' 'dhsbaseballnj' 'AnthonyPPinto' '5feetoffashion' 'Grafh'
 'DJBEEBLACK' 'hrhwe1032' 'RaquelCion' 'BrewPubExplorer' 'lincolnwrites'
 'giordanobc' 'NomInNY' 'TAsterisk' 'RobHBedford' 'imdjencore'
 'everytract' 'stevelauro' 'M97Cos' 'choppy2984' 'Majikonline'
 'JohnnyBarfly' 'RoyRuger' 'RRWhiskySpirits' 'harisamin' 'lentaminen'
 'Katluck125' 'TotalTrafficNYC' 'SsmBoutique40' 'billfelty' 'BienRealty'
 'Dr_Fiorillo' 'huntingforjoy' 'Home_Zuh' 'Mirjana13nyc' 'PaneraCareers'
 'JoeFleeNY' 'OWWRNY' 'drrichardreish' 'ctbeertours' 'citygrl33'
 'sonic13oom' 'parkslope5thave' 'GAGA_glitz' 'CTDOT_District3'
 'pop_amargaritav']
79

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from utils.Tweets_location import Tweets_location

In [6]:
t = Tweets_location()
d = t.get_tweets_location('511NY', 50)
d

,date,content,coordinates,place
0,2021-06-17 21:23:45+00:00,Updated: Incident on #NewJerseyTurnpikeEastern...,"{'longitude': -74.055982, 'latitude': 40.780892}","{'fullName': 'Secaucus, NJ', 'name': 'Secaucus..."
0,2021-06-17 21:23:44+00:00,Updated: Incident on #NJ24 EB from West of Exi...,"{'longitude': -74.358267, 'latitude': 40.735558}","{'fullName': 'Summit, NJ', 'name': 'Summit', '..."
0,2021-06-17 21:23:44+00:00,Updated: Incident on #NJ17 SB from North of Ri...,"{'longitude': -74.079592, 'latitude': 40.969969}","{'fullName': 'Paramus, NJ', 'name': 'Paramus',..."
0,2021-06-17 21:23:44+00:00,Updated: Incident on #NJ4 EB from River Rd to ...,"{'longitude': -74.027202, 'latitude': 40.899843}","{'fullName': 'Teaneck, NJ', 'name': 'Teaneck',..."
0,2021-06-17 21:23:43+00:00,Updated: Incident on #NJ17 NB from I-80 to Pas...,"{'longitude': -74.067667, 'latitude': 40.886227}","{'fullName': 'Lodi, NJ', 'name': 'Lodi', 'type..."
0,2021-06-17 21:23:43+00:00,Updated: Incident on #NJ4 WB from Queen Anne R...,"{'longitude': -74.032016, 'latitude': 40.904743}","{'fullName': 'Hackensack, NJ', 'name': 'Hacken..."
0,2021-06-17 21:23:43+00:00,Updated: Incident on #NJ21 NB from North of Ex...,"{'longitude': -74.116662, 'latitude': 40.871307}","{'fullName': 'Passaic, NJ', 'name': 'Passaic',..."
0,2021-06-17 21:23:43+00:00,Incident on #I495 WB from Exit 40W - State Rou...,"{'longitude': -73.572898, 'latitude': 40.779098}","{'fullName': 'Old Westbury, NY', 'name': 'Old ..."
0,2021-06-17 21:23:43+00:00,Updated: Incident on #NJ138 WB from NJ 18 to A...,"{'longitude': -74.072405, 'latitude': 40.17133}","{'fullName': 'Wall, NJ', 'name': 'Wall', 'type..."
0,2021-06-17 21:23:42+00:00,Closure on #SouthernStateParkway WB at Exit 31...,"{'longitude': -73.4557, 'latitude': 40.7058}","{'fullName': 'North Massapequa, NY', 'name': '..."
0,2021-06-17 21:23:42+00:00,Incident on #NewJerseyTurnpikeEasternSpur at I...,"{'longitude': -74.057139, 'latitude': 40.77806}","{'fullName': 'Secaucus, NJ', 'name': 'Secaucus..."
0,2021-06-17 21:23:42+00:00,Cleared: Construction on #I790 Both directions...,"{'longitude': -75.2382, 'latitude': 43.1087}","{'fullName': 'Utica, NY', 'name': 'Utica', 'ty..."
0,2021-06-17 21:23:42+00:00,Cleared: Incident on #I95NewEnglandThruway SB ...,"{'longitude': -73.667335, 'latitude': 40.988034}","{'fullName': 'Rye, NY', 'name': 'Rye', 'type':..."
0,2021-06-17 21:23:41+00:00,Cleared: Incident on #NY22 NB at CR 61,"{'longitude': -73.37779, 'latitude': 43.097307}","{'fullName': 'New York, USA', 'name': 'New Yor..."
0,2021-06-17 21:21:42+00:00,Updated: Incident on #US9 NB from CR 626/Cross...,"{'longitude': -74.220739, 'latitude': 40.05386}","{'fullName': 'Lakewood, NJ', 'name': 'Lakewood..."
0,2021-06-17 21:21:41+00:00,Updated: Incident on #NJ36 SB at NJ 35 https:/...,"{'longitude': -74.052744, 'latitude': 40.290869}","{'fullName': 'Eatontown, NJ', 'name': 'Eatonto..."
0,2021-06-17 21:21:40+00:00,Incident on #I280 EB at East of Exit 13 - Oran...,"{'longitude': -74.184171, 'latitude': 40.750958}","{'fullName': 'Newark, NJ', 'name': 'Newark', '..."
0,2021-06-17 21:21:40+00:00,Incident on #NJ18 SB from New St to North of C...,"{'longitude': -74.439144, 'latitude': 40.493332}","{'fullName': 'New Brunswick, NJ', 'name': 'New..."
0,2021-06-17 21:21:40+00:00,Cleared: Incident on #HenryHudsonBridge SB,"{'longitude': -73.922023, 'latitude': 40.877488}","{'fullName': 'Bronx, NY', 'name': 'Bronx', 'ty..."
0,2021-06-17 21:19:40+00:00,Updated: Incident on #NewJerseyTurnpikeWestern...,"{'longitude': -74.061526, 'latitude': 40.810764}","{'fullName': 'Carlstadt, NJ', 'name': 'Carlsta..."
0,2021-06-17 21:19:40+00:00,Updated: Construction on #US30 WB from East of...,"{'longitude': -74.628128, 'latitude': 39.515275}","{'fullName': 'Egg Harbor City, NJ', 'name': 'E..."
0,2021-06-17 21:19:39+00:00,Updated: Incident on #US9 SB at Taylors Mills ...,"{'longitude': -74.303839, 'latitude': 40.303074}","{'fullName': 'Yorketown, NJ', 'name': 'Yorketo..."
0,2021-06-17 21:19:39+00:00,Updated: Construction on #US30 EB from CR 623/...,"{'longitude': -74.715912, 'latitude': 39.576316}","{'fullName': 'New Jersey, USA', 'name': 'New J..."
0,2021-06-17 21:19:38+00:00,Incident on #I87Northway NB from Exit 15; NY 5...,"{'longitude': -73.750677, 'latitude': 43.092307}","{'fullName': 'Saratoga Springs, NY', 'name': '..."
0,2021-06-17 21:19:11+00:00,Cleared: Construction on #Route5 EB,"{'longitude': -78.84675, 'latitude': 42.79283}","{'fullName': 'Blasdell, NY', 'name': 'Blasdell..."
0,2021-06-17 21:17:39+00:00,Incident on #I84 WB at Exit 61 - State Hwy 311...,"{'longitude': -73.649421, 'latitude': 41.4743}","{'fullName': 'Patterson, NY', 'name': 'Patters..."
0,2021-06-17 21:17:39+00:00,Updated: Incident on #LincolnTunnel EB from Ne...,"{'longitude': -74.016109, 'latitude': 40.765163}","{'fullName': 'New Jersey, USA', 'name': 'New J..."
0,2021-06-17 21:17:39+00:00,Incident on #TaconicStateParkway SB at Exit 47...,"{'longitude': -73.788902, 'latitude': 41.668201}","{'fullName': 'New York, USA', 'name': 'New Yor..."
0,2021-06-17 21:17:39+00:00,Updated: Incident on #CT15 NB at 1.26 miles be...,"{'longitude': -73.671743, 'latitude': 41.064745}","{'fullName': 'Connecticut, USA', 'name': 'Conn..."
0,2021-06-17 21:17:39+00:00,Incident on #GardenStateParkway SB from South ...,"{'longitude': -74.099737, 'latitude': 40.335366}","{'fullName': 'Lincroft, NJ', 'name': 'Lincroft..."
0,2021-06-17 21:17:39+00:00,Cleared: Construction on #I490 WB from South A...,"{'longitude': -77.607086, 'latitude': 43.151101}","{'fullName': 'New York, USA', 'name': 'New Yor..."
0,2021-06-17 21:17:38+00:00,Incident on #NJ4 EB at West of Teaneck Rd http...,"{'longitude': -74.004731, 'latitude': 40.890897}","{'fullName': 'Teaneck, NJ', 'name': 'Teaneck',..."
0,2021-06-17 21:17:38+00:00,Cleared: Incident on #I90 WB at Exit 4; NY 85,"{'longitude': -73.80917, 'latitude': 42.687547}","{'fullName': 'New York, USA', 'name': 'New Yor..."
0,2021-06-17 21:17:38+00:00,Cleared: Incident on #I787 NB at Exit 9E; NY 7...,"{'longitude': -73.699007, 'latitude': 42.737902}","{'fullName': 'Latham, NY', 'name': 'Latham', '..."
0,2021-06-17 21:15:38+00:00,Updated: Incident on #I95NewEnglandThruway SB ...,"{'longitude': -73.667335, 'latitude': 40.988034}","{'fullName': 'Rye, NY', 'name': 'Rye', 'type':..."
0,2021-06-17 21:15:38+00:00,Updated: Incident on #HollandTunnel EB from Ne...,"{'longitude': -74.030858, 'latitude': 40.72866}","{'fullName': 'Jersey City, NJ', 'name': 'Jerse..."
0,2021-06-17 21:15:37+00:00,Cleared: Incident on #I87MajorDeeganExpressway...,"{'longitude': -73.924403, 'latitude': 40.806891}","{'fullName': 'Bronx, NY', 'name': 'Bronx', 'ty..."
0,2021-06-17 21:15:37+00:00,Construction on #I295 NB at North of Exit 22 -...,"{'longitude': -75.157164, 'latitude': 39.859239}","{'fullName': 'Thorofare, NJ', 'name': 'Thorofa..."
0,2021-06-17 21:15:37+00:00,Cleared: Incident on #I95NewEnglandThruway NB ...,"{'longitude': -73.735152, 'latitude': 40.962587}","{'fullName': 'Mamaroneck, NY', 'name': 'Mamaro..."
0,2021-06-17 21:15:37+00:00,Incident on #CT15 SB at 0.25 miles beyond Exit...,"{'longitude': -73.07914, 'latitude': 41.249219}","{'fullName': 'Milford, CT', 'name': 'Milford',..."
0,2021-06-17 21:15:37+00:00,Cleared: Incident on #AdirondackMountainReserv...,"{'longitude': -73.764188, 'latitude': 44.150407}","{'fullName': 'New York, USA', 'name': 'New Yor..."
0,2021-06-17 21:15:37+00:00,Cleared: Incident on #GardenStateParkway SB fr...,"{'longitude': -74.088541, 'latitude': 40.285376}","{'fullName': 'Tinton Falls, NJ', 'name': 'Tint..."
0,2021-06-17 21:15:37+00:00,Cleared: Incident on #GardenStateParkway SB fr...,"{'longitude': -74.082022, 'latitude': 40.251449}","{'fullName': 'Tinton Falls, NJ', 'name': 'Tint..."
0,2021-06-17 21:13:37+00:00,Incident on #RLine from Queens Plaza to Jackso...,"{'longitude': -73.937243, 'latitude': 40.748973}","{'fullName': 'Queens, NY', 'name': 'Queens', '..."
0,2021-06-17 21:13:37+00:00,Construction on #NJ33 WB at Halls Mill Rd http...,"{'longitude': -74.24585, 'latitude': 40.236398}","{'fullName': 'West Freehold, NJ', 'name': 'Wes..."
0,2021-06-17 21:13:37+00:00,Cleared: Construction on #US30 EB from NJ 87/M...,"{'longitude': -74.439217, 'latitude': 39.373295}","{'fullName': 'Atlantic City, NJ', 'name': 'Atl..."
0,2021-06-17 21:13:37+00:00,Incident on #MLine NB from Queens Plaza to Jac...,"{'longitude': -73.937243, 'latitude': 40.748973}","{'fullName': 'Queens, NY', 'name': 'Queens', '..."

In [7]:
d.shape

(47, 4)

In [58]:
t = tweets()
d = t.get_tweets_location('BlazeMusicNet', 500)

,date,content,coordinates,place
0,2021-06-17 14:59:43+00:00,🔥🔥💪👉 Repost Via @haracakikooficial La Gloria e...,"{'longitude': -69.8946, 'latitude': 18.4727}","{'fullName': 'anto Domingo de Guzmán, Dominica..."
0,2021-06-17 14:41:59+00:00,🔥🔥💪👉 Repost Via @kalyocho Ñera 🥶 @daya._02 ❤️ ...,"{'longitude': -69.8946, 'latitude': 18.4727}","{'fullName': 'anto Domingo de Guzmán, Dominica..."
0,2021-06-17 04:43:39+00:00,"Just posted a video @ Santo Domingo, Dominican...","{'longitude': -69.8946, 'latitude': 18.4727}","{'fullName': 'anto Domingo de Guzmán, Dominica..."
0,2021-06-17 04:03:01+00:00,"Just posted a photo @ New York, New York https...","{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
0,2021-06-17 03:27:41+00:00,DISPONIBLE YA: @elchobbi Da Su Opinion Sobre L...,"{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
...,...,...,...,...
0,2021-05-01 23:00:54+00:00,"Just posted a video @ New York, New York https...","{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
0,2021-05-01 22:52:16+00:00,DISPONIBLE YA: #CekyViciny ft #LaPerversa y #E...,"{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
0,2021-05-01 22:32:06+00:00,SIGUE DANDOLE PLAY: @haracakikooficial - Pompo...,"{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
0,2021-05-01 22:11:54+00:00,DISPONIBLE YA: @lamaterialista1 - Mejor Sola (...,"{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."
0,2021-05-01 21:13:34+00:00,DISPONIBLE YA: #DJChuloNYC #yailinlamasviral #...,"{'longitude': -74.0064, 'latitude': 40.7142}","{'fullName': 'Manhattan, NY', 'name': 'Manhatt..."